<?php

/**
 * ShopcrawlShopTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ShopcrawlShopTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ShopcrawlShopTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ShopcrawlShop');
    }
}