<?php

/**
 * ShopcrawlProductTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ShopcrawlProductTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ShopcrawlProductTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ShopcrawlProduct');
    }
}