<?php

/**
 * ShopcrawlCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ShopcrawlCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ShopcrawlCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ShopcrawlCategory');
    }

    public function findOrCreateOneByName($name) {


        $category = $this->findOneByName($name);
        if (!$category) {
            $category = new ShopcrawlCategory();
            $category
                ->setName($name)
                ->save();
        }

        return $category;
    }
}